### PR TITLE
Refactor of converter methods, and make nested view works

### PR DESCRIPTION
**Pull request by joaogbcravo**
This is a big pull request. It refactors some problems related with pep8, and function calls.
One of the big differences is to reuse
yaml_dict variable that is redefined as yaml_dict[0]['view'], so we don't repeat this verbose and slower dictionary fetch.

### CODE REVIEW

**Comment by piyush0101** [comment]
@joaogbcravo Thanks for this refactoring. Looks great.

**Comment by piyush0101** [comment]
@joaogbcravo Nested views are still not fully functional. I just haven't gotten around to implement them completely.

**Comment by joaogbcravo** [comment]
What it is missing from the nested views?

**Comment by piyush0101** [comment]
Oops. My bad. Following lines should be good and produce the desired output. Thanks for implementing this. 

 for yaml_view in yaml_dict['views']:
        view = converter.convert_yaml_dict_to_xml(yaml_view['view'])
        views_section.append(view)

**Comment by joaogbcravo** [comment]
Can you please do a release?

**Comment by joaogbcravo** [comment]
Can you please do a release?

**Comment by piyush0101** [comment]
Done.

**Pull request merged**
