### PR TITLE
Fix 'regex' support in ListView

### PR DESCRIPTION
**Pull request by ghost**
- set_regex in list_view.py to also support "regex"
- adding ListView tests for "regex"

### CODE REVIEW

**Comment by hrubi** [comment]
I think that only one test is sufficient. The `list_view_regex_multiplejobs` seems like a superset of the `list_view_regex`. I'd just keep the `list_view_regex` and test there one explicit job + one regex.

Or do you see some added value in testing the list view with the regex only? Is there added value when testing regex present together with _multiple_ jobs?

**Comment by ghost** [comment]
I added the extra test because I moved "regex" from "jobs" section to the top level in the fixture xml.

**Comment by michalvanco** [comment]
Thanks @luv and @hrubi.

**Comment by aRTURIUSS** [comment]
@michalvanco Hi, Could you please provide information about the next release? When will it be? Thank you!

**Pull request merged**
